name: moment_env
channels:
  - pytorch
  - nvidia
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - pandas=1.3.2
  - pip=21.2.4
  - python=3.9.6
  - pytorch=1.9.0
  - torchaudio=0.9.0
  - torchvision=0.10.0
  - pip:
    - ffmpeg-python
    - ftfy
    - regex
    - tqdm
    - ipython
    - easydict
    - tabulate
    - tensorboardx
    - scikit-learn