// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdnXNZUGBGO1aPCTrYU37rLdil6uuA3i4',
    appId: '1:829277582950:web:4b3d9b3190f4c210441fa7',
    messagingSenderId: '829277582950',
    projectId: 'editor-ai-390116',
    authDomain: 'editor-ai-390116.firebaseapp.com',
    storageBucket: 'editor-ai-390116.appspot.com',
    measurementId: 'G-8XSQCRFTHL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHHbs3QHM_c196HJ9YhTKIHSzxiDoy-CY',
    appId: '1:829277582950:android:49747fc5d772c992441fa7',
    messagingSenderId: '829277582950',
    projectId: 'editor-ai-390116',
    storageBucket: 'editor-ai-390116.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSmzZoEHrCHVDsKlrukscXVSCXi_Y-_EQ',
    appId: '1:829277582950:ios:7c3136c1588932d0441fa7',
    messagingSenderId: '829277582950',
    projectId: 'editor-ai-390116',
    storageBucket: 'editor-ai-390116.appspot.com',
    iosClientId: '829277582950-glqv23tc6t3p4alk8hjq66t9oonhnelj.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiditorWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSmzZoEHrCHVDsKlrukscXVSCXi_Y-_EQ',
    appId: '1:829277582950:ios:d413be486166cd91441fa7',
    messagingSenderId: '829277582950',
    projectId: 'editor-ai-390116',
    storageBucket: 'editor-ai-390116.appspot.com',
    iosClientId: '829277582950-0kp081h8s3sih28nr5vada3vtf6e3s5q.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiditorWeb.RunnerTests',
  );
}
